### ISSUE TITLE
Returns null when trying to call accessSecretVersion method

### ISSUE THREAD

**Issue by vishvajit79** [googleapis/nodejs-secret-manager#33] opened 2020-01-28 04:20 UTC
I am using nodev12.14.1
I have a node typescript project and I am calling the accessSecretVersion  with my secret and it return null

```js
import { SecretManagerServiceClient } from '@google-cloud/secret-manager';
import { injectable } from 'inversify';

import { config } from '../config';
import logger from '../server/utils/logger';
import { InterfaceSecretManagerPlugin } from './secret-manager.interface';

const client = new SecretManagerServiceClient();

const secrets: { [key: string]: string } = {};

@injectable()
export class SecretManagerPlugin implements InterfaceSecretManagerPlugin {
  public async initSecret(key: string): Promise<void> {
    try {
      logger.info(`Initializing secret: ${key} started`);
      const [accessResponse] = await client.accessSecretVersion({
        name: config.googleCloudConfig.secrets[key]
      });
      const responsePayload: string | null =
        accessResponse && accessResponse.payload && accessResponse.payload.data
          ? accessResponse.payload.data.toString()
          : null;
      if (responsePayload) {
        secrets[key] = responsePayload;
        logger.info(`Initializing secret: ${key} finished`);
      } else {
        logger.error(`Initializing secret: ${key} failed`);
      }
    } catch (error) {
      logger.error(`Error while initializing secret: ${key}`, {
        error,
        secretName: key
      });
    }
  }

  public async getSecretString(key: string): Promise<string | null> {
    logger.info(`Getting secret: ${key} data`);
    if (secrets[key]) {
      logger.info(`Done getting secret: ${key} data`);
      return secrets[key];
    }
    logger.info(`Secret: ${key} not found in the storage. Calling initSecret`);
    await this.initSecret(key);
    logger.info(`Done getting secret: ${key} data`);
    return secrets[key];
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  public async getSecretJson(key: string): Promise<any> {
    const secretString = await this.getSecretString(key);
    try {
      if (secretString) {
        return JSON.parse(secretString);
      }
    } catch (error) {
      logger.error(`Error while parsing secret: ${key} to JSON object`, {
        error,
        secretName: key
      });
    }
    return null;
  }
}

```

**Comment by bcoe** [comment] 2020-01-28 18:30
Nothing is immediately jumping out at me I'm doing almost the exact same thing [here](https://github.com/googleapis/repo-automation-bots/blob/master/packages/publish/src/publish.ts#L143) @vishvajit79, perhaps try testing by populating `name` manually and working backwards; one thought, perhaps you accidentally set a different secret than you are accessing?

**Comment by bcoe** [comment] 2020-01-28 18:34
@sethvargo anything jump out at you here?

**Comment by sethvargo** [comment] 2020-01-28 20:17
Not really. @vishvajit79 How did you create the secret?

**Comment by vishvajit79** [comment] 2020-01-28 23:46
> 
> 
> Nothing is immediately jumping out at me I'm doing almost the exact same thing [here](https://github.com/googleapis/repo-automation-bots/blob/master/packages/publish/src/publish.ts#L143) @vishvajit79, perhaps try testing by populating `name` manually and working backwards; one thought, perhaps you accidentally set a different secret than you are accessing?

Yes, I tried manually populating the name  but still the same. Also, I tried to use wrong secret and it was throwing error instead of returning null. If I use gcloud command line, then it get the data in the console. Something wrong with the node or maybe my environment setup, I believe

**Comment by vishvajit79** [comment] 2020-01-28 23:46
> 
> 
> Not really. @vishvajit79 How did you create the secret?

Manually going to the secret manager console in gcloud

**Comment by vishvajit79** [comment] 2020-01-29 00:30
Even I tried to create a new secret from node and I got this error
`metadata: {
    error: Error: 3 INVALID_ARGUMENT: Resource ID [] is not in a valid format.
        at Object.callErrorFromStatus (D:\Startup\backend\microservice-template\node_modules\@grpc\grpc-js\build\src\call.js:30:26)
        at Http2CallStream.<anonymous> (D:\Startup\backend\microservice-template\node_modules\@grpc\grpc-js\build\src\client.js:96:33)
        at Http2CallStream.emit (events.js:228:7)
        at D:\Startup\backend\microservice-template\node_modules\@grpc\grpc-js\build\src\call-stream.js:97:22
        at processTicksAndRejections (internal/process/task_queues.js:76:11) {
      code: 3,
      details: 'Resource ID [] is not in a valid format.',
      metadata: Metadata {
        internalRepr: Map {
          'grpc-server-stats-bin' => [ <Buffer 00 00 ce 79 da 00 00 00 00 00> ]
        },
        options: {}
      }
    },
    key: 'nemo-database'
  },`

**Comment by sethvargo** [comment] 2020-01-29 01:07
What is the value of `config.googleCloudConfig.secrets[key]`?

**Comment by vishvajit79** [comment] 2020-01-29 02:03
> 
> 
> What is the value of `config.googleCloudConfig.secrets[key]`?

> projects/1096887738631/secrets/nemo-database-dev/versions/latest

**Comment by sethvargo** [comment] 2020-01-29 02:08
```Resource ID [] is not in a valid format.``` makes me think it is perhaps null or undefined at some point.

**Comment by vishvajit79** [comment] 2020-01-29 02:31
Here's the link to my repo.
https://github.com/vishvajit79/microservice-template/blob/master/src/plugins/secret-manager.plugin.ts#L14

Please let me know if you find something

**Comment by sethvargo** [comment] 2020-01-29 03:09
You aren't setting the secretId on creation:

```difff
diff --git a/src/plugins/secret-manager.plugin.ts b/src/plugins/secret-manager.plugin.ts
index 255c2f1..1498482 100644
--- a/src/plugins/secret-manager.plugin.ts
+++ b/src/plugins/secret-manager.plugin.ts
@@ -69,9 +69,12 @@ export class SecretManagerPlugin implements InterfaceSecretManagerPlugin {
       logger.info('Creating secret');
       const [secret] = await client.createSecret({
         parent: `projects/${config.googleCloudConfig.projectId}`,
+        secretId: config.googleCloudConfig.secrets[key],
         secret: {
-          name: config.googleCloudConfig.secrets[key]
-        }
+          replication: {
+            automatic: {},
+          },
+        },
       });
       logger.info('Secret created', { secret });
       logger.info('Adding secret version');
```

You can see samples for creating, adding, and access secrets in this repo.

**Comment by vishvajit79** [comment] 2020-01-29 03:20
> 
> 
> You aren't setting the secretId on creation:
> 
> ```
> diff --git a/src/plugins/secret-manager.plugin.ts b/src/plugins/secret-manager.plugin.ts
> index 255c2f1..1498482 100644
> --- a/src/plugins/secret-manager.plugin.ts
> +++ b/src/plugins/secret-manager.plugin.ts
> @@ -69,9 +69,12 @@ export class SecretManagerPlugin implements InterfaceSecretManagerPlugin {
>        logger.info('Creating secret');
>        const [secret] = await client.createSecret({
>          parent: `projects/${config.googleCloudConfig.projectId}`,
> +        secretId: config.googleCloudConfig.secrets[key],
>          secret: {
> -          name: config.googleCloudConfig.secrets[key]
> -        }
> +          replication: {
> +            automatic: {},
> +          },
> +        },
>        });
>        logger.info('Secret created', { secret });
>        logger.info('Adding secret version');
> ```
> 
> You can see samples for creating, adding, and access secrets in this repo.

I updated the repo to add secretId and I still get null as the response
`{
  message: 'Creating secret',      
  level: 'info',
  timestamp: '2020-01-28 22:18:57',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Secret created',       
  level: 'info',
  timestamp: '2020-01-28 22:18:58',
  label: 'index.js',
  metadata: { secret: null },      
  secret: null
}
{
  message: 'Adding secret version',
  level: 'info',
  timestamp: '2020-01-28 22:18:58',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Added secret version',
  level: 'info',
  timestamp: '2020-01-28 22:18:58',
  label: 'index.js',
  metadata: { version: null },
  version: null
}
{
  message: 'Initializing secret: nemoDatabase started',
  level: 'info',
  timestamp: '2020-01-28 22:18:58',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Initializing secret: nemoDatabase failed',
  level: 'error',
  timestamp: '2020-01-28 22:18:58',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Getting secret: nemoDatabase data',
  level: 'info',
  timestamp: '2020-01-28 22:18:58',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Secret: nemoDatabase not found in the storage. Calling initSecret',
  level: 'info',
  timestamp: '2020-01-28 22:18:58',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Creating secret',
  level: 'info',
  timestamp: '2020-01-28 22:18:58',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Error while creating secert and version',
  level: 'error',
  timestamp: '2020-01-28 22:18:58',
  label: 'index.js',
  metadata: {
    error: Error: 6 ALREADY_EXISTS: Secret [projects/1096887738631/secrets/nemoDatabase] already exists.
        at Object.callErrorFromStatus (D:\Startup\backend\microservice-template\node_modules\@grpc\grpc-js\build\src\call.js:30:26)
        at Http2CallStream.<anonymous> (D:\Startup\backend\microservice-template\node_modules\@grpc\grpc-js\build\src\client.js:96:33)
        at Http2CallStream.emit (events.js:228:7)
        at D:\Startup\backend\microservice-template\node_modules\@grpc\grpc-js\build\src\call-stream.js:97:22
        at processTicksAndRejections (internal/process/task_queues.js:76:11) {
      code: 6,
      details: 'Secret [projects/1096887738631/secrets/nemoDatabase] already exists.',
      metadata: Metadata {
        internalRepr: Map {
          'grpc-server-stats-bin' => [ <Buffer 00 00 5e 2a 30 03 00 00 00 00> ]
        },
        options: {}
      }
    },
    key: 'nemoDatabase'
  },
  error: Error: 6 ALREADY_EXISTS: Secret [projects/1096887738631/secrets/nemoDatabase] already exists.
      at Object.callErrorFromStatus (D:\Startup\backend\microservice-template\node_modules\@grpc\grpc-js\build\src\call.js:30:26)
      at Http2CallStream.<anonymous> (D:\Startup\backend\microservice-template\node_modules\@grpc\grpc-js\build\src\client.js:96:33)
      at Http2CallStream.emit (events.js:228:7)
      at D:\Startup\backend\microservice-template\node_modules\@grpc\grpc-js\build\src\call-stream.js:97:22
      at processTicksAndRejections (internal/process/task_queues.js:76:11) {
    code: 6,
    details: 'Secret [projects/1096887738631/secrets/nemoDatabase] already exists.',
    metadata: Metadata {
      internalRepr: Map {
        'grpc-server-stats-bin' => [ <Buffer 00 00 5e 2a 30 03 00 00 00 00> ]
      },
      options: {}
    }
  },
  key: 'nemoDatabase'
}
{
  message: 'Initializing secret: nemoDatabase started',
  level: 'info',
  timestamp: '2020-01-28 22:18:58',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Initializing secret: nemoDatabase failed',
  level: 'error',
  timestamp: '2020-01-28 22:18:58',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Done getting secret: nemoDatabase data',
  level: 'info',
  timestamp: '2020-01-28 22:18:58',
  label: 'index.js',
  metadata: {}
}
Unhandled rejection TypeError: Cannot read property 'database' of null
    at SequelizePlugin.<anonymous> (D:\Startup\backend\microservice-template\dist\plugins\sequelize.plugin.js:39:43)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Startup\backend\microservice-template\dist\plugins\sequelize.plugin.js:17:58)  
    at tryCatcher (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)`

**Comment by vishvajit79** [comment] 2020-01-29 03:30
After removing create method, when I only have accessSecretVersion, I get this logs

`
{
  message: 'Initializing secret: nemoDatabase started',
  level: 'info',
  timestamp: '2020-01-28 22:28:40',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Initializing secret: nemoDatabase failed',
  level: 'error',
  timestamp: '2020-01-28 22:28:41',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Getting secret: nemoDatabase data',
  level: 'info',
  timestamp: '2020-01-28 22:28:41',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Secret: nemoDatabase not found in the storage. Calling initSecret',
  level: 'info',
  timestamp: '2020-01-28 22:28:41',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Initializing secret: nemoDatabase started',
  level: 'info',
  timestamp: '2020-01-28 22:28:41',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Initializing secret: nemoDatabase failed',
  level: 'error',
  timestamp: '2020-01-28 22:28:41',
  label: 'index.js',
  metadata: {}
}
{
  message: 'Done getting secret: nemoDatabase data',
  level: 'info',
  timestamp: '2020-01-28 22:28:41',
  label: 'index.js',
  metadata: {}
}
Unhandled rejection TypeError: Cannot read property 'database' of null
    at SequelizePlugin.<anonymous> (D:\Startup\backend\microservice-template\dist\plugins\sequelize.plugin.js:39:43)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Startup\backend\microservice-template\dist\plugins\sequelize.plugin.js:17:58)  
    at tryCatcher (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\Startup\backend\microservice-template\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
`

**Comment by sethvargo** [comment] 2020-01-29 03:36
Hi @vishvajit79 

Please format your code using [markdown](https://guides.github.com/features/mastering-markdown/). Particularly for large stack traces, please use triple backticks to make it easier to read.

When I execute your code, I get ```SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306```, which is probably correct because I don't have a database running.

**Comment by vishvajit79** [comment] 2020-01-29 03:41
Then does it have to do with my gcloud sdk and the access? Were you able to create and receive the secret?

**Comment by sethvargo** [comment] 2020-01-29 03:45
It's difficult to say. I don't fully understand the workflow, but my log output seems to indicate that I successfully accessed the secret.

**Comment by vishvajit79** [comment] 2020-01-30 01:18
I tried to add more debug logs and I keep getting 
```
"Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information."
```

I am on windows machine. I followed the steps from the link and didn't work. I also tried running `gcloud auth application-default login` but still the same issue. Can you help with that?

**Comment by bcoe** [comment] 2020-01-30 02:02
@vishvajit79 could you try setting the environment variable `GOOGLE_APPLICATION_CREDENTIALS`, following the instructions [here](https://cloud.google.com/docs/authentication/getting-started).

**Comment by vishvajit79** [comment] 2020-02-01 05:44
Thanks, it started working now! I had the environment variable since the beginning but it was something to do with my environment setup I guess.

**Comment by bcoe** [comment] 2020-02-03 05:35
@vishvajit79 awesome, I'm glad you're unblocked.

**Comment by vishvajit79** [comment] 2020-02-05 01:14
Accessing google secret manager sometimes returns null after the issue was resolved but now it has stopped working completely. I have also added a retry logic that tries to fetch the secret10 times if it fails. Is it because it is still in the beta?

**Comment by sethvargo** [comment] 2020-02-05 01:17
Hi @vishvajit79 

It's difficult to say without seeing the code and understanding the steps you have taken. Google Secret Manager is fully operational and has not experienced any outages. I'm also personally using it in a few projects and it has never returned null when accessing a secret.

**Comment by vishvajit79** [comment] 2020-02-05 01:21
Is there a way to debug the call being made as it is not throwing error. It just returns null

**Comment by sethvargo** [comment] 2020-02-05 03:21
Can you please share your updated code?

**Comment by vishvajit79** [comment] 2020-02-05 13:59
Sure here is the repo link [https://gitlab.com/find-nemo/microservice-template](https://gitlab.com/find-nemo/microservice-template)

**Comment by sethvargo** [comment] 2020-02-05 15:29
Hi @vishvajit79 I'm able to reproduce the issue on your code, but I honestly have no idea what's going on. I cannot reproduce the issue outside of your code, which makes me believe it's a dependency issue or something is not properly initializing further up your stack.

What happens if you add the following to the bottom of `secret-manager.plugin.ts` and run it?

```ts
const test = async () => {
  const p = new SecretManagerPlugin();
  await p.initSecret('nemoDatabase');
}

test();
```

In my testing, this properly fetched the secret. However, when I run your code (`npm run local`), the secret returns nil. My guess is that one of your dependencies is messing with the promise.

It would be really helpful if you could narrow down the problem to a single, runnable node.js file that we could use to reproduce it on our end. Your current application has too many variables and layers of indirection to adequately debug.

**Comment by bcoe** [comment] 2020-02-05 21:33
@sethvargo @vishvajit79 I would experiment with dropping the bluebird dependency, this shims promises globally, and has caused problems in the past.

**Comment by vishvajit79** [comment] 2020-02-06 00:34
Yes, it was due to a bluebird. When I removed it globally, it started working again. Thanks for the response

**Comment by JustinBeckwith** [comment] 2020-10-31 19:10
Awesome :) Looks like this is resolved, so I'm going to go ahead and close this out.  If you are still running into problems, please do let us know!

**Closed by JustinBeckwith** 2020-10-31 19:10 UTC
Labels: api: secretmanager, type: question
